# Generated by Django 2.1.3 on 2020-07-15 12:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assigned', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), size=10)),
            ],
        ),
    ]
