# Generated by Django 2.1.3 on 2020-07-15 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedlist',
            name='assigned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=10),
        ),
    ]
